### ISSUE TITLE
Cannot start helicopter

### ISSUE THREAD

**Issue by trollmad3** [weltensturm/wac#122]
I cannot start the WAC helicopters with the steam workshop version. I press `R` and it does not start, + the controls are missing from the menu.

**Comment by weltensturm** [comment]
Fixed clients not calling Initialize consistently

**Comment by weltensturm** [comment]
If it's still broken for you (it probably is, since missing controls looks like another issue) it most likely is a conflict with other addons. Try WAC Aircraft with a clean GMod install (no other addons) to confirm this.
